
package vue;

import javax.swing.table.AbstractTableModel;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author Maïlys
 */
public class Calendrier extends javax.swing.JFrame {

    ModeleCalendrier modele;
    /**
     * Creates new form Calendrier
     */
    public Calendrier() {
        initComponents();
        modele = new ModeleCalendrier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choixAnnee = new javax.swing.JComboBox();
        choixSemaine = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        choixAnnee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016"}));
        choixAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixAnneeActionPerformed(evt);
            }
        });

        choixSemaine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semaine 1", "Semaine 2", "Semaine 3", "Semaine 4", "Semaine 5", "Semaine 6", "Semaine 7", "Semaine 8", "Semaine 9", "Semaine 10", "Semaine 11", "Semaine 12", "Semaine 13", "Semaine 14", "Semaine 15", "Semaine 16", "Semaine 17", "Semain 18", "Semaine 19", "Seamine 20", "Semaine 20", "Semaine 21", "Semaine 22", "Semaine 23", "Semaine 24", "Semaine 25", "Semaine 26", "Semaine 27", "Semaine 28", "Semaine 29", "Semaine 30", "Semaine 40", "Semaine 41", "Semaine 42", "Semaine 43", "Semaine 44", "Semaine 45", "Semaine 46", "Semaine 47", "Semaine 48", "Semaine 49", "Semaine 50", "Semaine 51", "Semaine 52" }));
        choixSemaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixSemaineActionPerformed(evt);
            }
        });

        jTable1.setModel(modele);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(choixSemaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choixAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choixSemaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixSemaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixSemaineActionPerformed

    }//GEN-LAST:event_choixSemaineActionPerformed

    private void choixAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixAnneeActionPerformed
    }//GEN-LAST:event_choixAnneeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendrier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendrier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox choixAnnee;
    private javax.swing.JComboBox choixSemaine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
private class ModeleCalendrier extends AbstractTableModel{
        private final String [] entetes = {"Lundi", "Mardi","Mercredi", "Jeudi","Vendredi", "Samedi", "Dimanche"};

        public ModeleCalendrier() {
        }

        @Override
        public String getColumnName(int column) {
           return entetes[column]; 
        }
        
        @Override
        public int getRowCount() {
           return 2; 
        }

        @Override
        public int getColumnCount() {
            return entetes.length;
        }
//Observer-vue : pour créer les cours
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch ()
        }
}

}
